server:
  address: localhost  # 192.168.0.103
  port: 8080
spring:
  jpa:
    open-in-view: false
  datasource:
    url: jdbc:h2:mem:communication-platform
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
jwt:
  secretKey: secret_key
  accessTokenExpirationMs: 86400000  # 24h
  refreshTokenExpirationMs: 86400000 # 24h
