server:
#  address: localhost
  address: 192.168.0.103
  port: 8080
spring:
  sql:
    init:
      mode: always
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:communication-platform
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
jwt:
  secretKey: secret_key
  accessTokenExpirationMs: 86400000  # 24h
  refreshTokenExpirationMs: 86400000 # 24h
